version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: wcquest_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wcquest
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  pgdata:
    
